apiVersion: v1
kind: policy
metadata:
  name: database-policy
spec:
  selector: app == 'database'
  ingress:
  - action: allow
    protocol: tcp
    source:
      selector: app == 'frontend'
    destination:
      ports:
      - 6379
