apiVersion: v1
kind: policy
metadata:
  name: database-policy
spec:
  selector: app == 'database'
  ingress:
  - action: allow
    source:
      selector: app == 'frontend'
    destination:
      port: 6379
  egress:
  - action: deny
