apiVersion: v1
kind: policy
metadata:
  name: frontend-policy
spec:
  selector: app == 'frontend'
  ingress:
  - action: allow
    source:
      net: 192.168.65.32/27
    destination:
      port: 80
  egress:
  - action: allow
    destination:
      selector: app == 'database'
      port: 6379
