apiVersion: v1
kind: policy
metadata:
  name: frontend-policy
spec:
  selector: app == 'frontend'
  ingress:
  - action: allow
    protocol: tcp
    source:
      net: 192.168.65.32/27
    destination:
      ports:
      - 80
  egress:
  - action: allow
    protocol: tcp
    destination:
      selector: app == 'database'
      ports:
      - 6379
